### ISSUE TITLE
Road map to v1

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/net-dns#20]
- [x] rename DnsReader/DnsWriter => WireReader/WireWriter
- [x] rename Class to DnsClass
- [x] rename to `master` to `presentation`
- [x] add PresentationReader
- [x] implement TSIG, TKey
- [x] Add a SecurityAlgoithm registry
- [x] Fix TODOs, or create an issue
- More articles
  - [x] describe serialisation
  - [x] describe the registries
  - [x] DSNSEC
